name: Bug 🐛
description: Create a new ticket for a bug 🐛
title: 🐛 [BUG] - <title>
labels: [bug 🐛]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please enter an explicit description of your issue.
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: input
    id: reprod-url
    attributes:
      label: Reproduction URL
      description: Please enter your GitHub URL to provide a reproduction of the issue.
      placeholder: ex. https://github.com/USERNAME/REPOSITORY
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: Reproduction steps
      description: Please enter an explicit description of how to reproduce the issue.
      value: |
        1. Go to ...
        2. Click on ...
        4. See error
      render: sh
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please copy and paste any relevant log output.
      render: sh
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: OS
      description: What is the impacted environment?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: false
