name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: '.commitlintrc'
      - name: Install dependencies
        run: npm ci
      - name: Check
        run: npm run check
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: error
          ignore_paths: node_modules
